[package]
name = "pci_fetch"
version = "0.1.0"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"
repository = "https://github.com/grtcdr/pci_fetch"
license-file = "LICENSE"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
