[package]
name = "pci_fetch"
description = "A pci.ids-compliant library for getting information about available PCI devices."
keywords = [ "pci", "fetch", "hardware" ]
version = "2.2.1"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"
repository = "https://github.com/grtcdr/pci_fetch"
license = "MIT"
readme = "README.md"
