[package]
name = "pci_fetch"
description = "Get information about connected PCI devices"
keywords = [ "pci", "fetch", "hardware" ]
version = "2.2.0"
authors = ["grtcdr <ba.tahaaziz@gmail.com>"]
edition = "2018"
repository = "https://github.com/grtcdr/pci_fetch"
license-file = "LICENSE"
readme = "README.md"
