name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install rust-fmt
        run: rustup component add rustfmt
      - name: Check Formatting
        run: cargo fmt -- --check  
      
